libsdl-org/sdl12-compat

src/SDL12_compat.c, src/SDL20_syms.h
This change adds unicode input support via the `SDL_TEXTINPUT` events.
These are turned into a number of new `KEYDOWN` events, one per input character. These generated events all have a sym of `SDLK_UNKNOWN,` so shouldn't register as spurious keyboard inputs. Normal key messages (i.e., those which did not originate with an `SDL_TEXTINPUT` event) now have a `unicode` value of 0 all the time.
It's not perfect yet (see below), but seems to be an improvement over just using the `keysym.sym` value, which didn't support things like using Shift to get uppercase letters.
Note that this also includes a basic UTF-8 decoder, which depends on  `SDL_MostSignificantBitIndex32()`. Since it's force-inlined, 
It also doesn't yet support codepoints greater than 0xFFFF, as we don't yet generate surrogate …
=> Basic unicode input support

src/SDL12_compat.c
Some games do some interesting things with `SDL_ListModes()`, `SDL_VideoModeOK()` and similar in order to choose and/or validate video modes.
In particular, [Darwinia, Defcon, and Multiwinia](https://www.introversion.co.uk/introversion/) all take the desktop mode's format (via `SDL_GetVideoInfo()->vfmt`), replace the `BitsPerPixel` field with their desired bpp, and then validate that `SDL_ListModes()` returns a list of modes. (They then goes on to verify the mode it selects with SDL_VideoModeOK(), and very aggressively falls back to 800×600 windowed at 16-bit. This is particularly annoying for Darwinia and Defcon, which need a restart after every mode change.)
With sdl12-compat, this never yields a valid mode under X11. By just checking if there's a mode with the same bit depth (which, …
=> SDL_ListModes: Treat formats with the same bpp as though they are identical

CMakeLists.txt
This adds minimal logic to support installing the library correctly
on various platforms when the install target is being used.
This makes it possible to build and install it for both native and
cross compile targets for Linux, macOS, and Windows.
=> Support installing the library

src/SDL12_compat.c
Some games (notably Uplink) only pass the unicode value to their text input code, and rely on it for some control characters. Since these are not part of the TEXTINPUT events, they need to be synthesised separately.
We support five such control characters:
- Backspace ('\b' / 0x08)
- Tab ('\t' / 0x09)
- Enter ('\r' / 0x0D)
- Shift+Enter ('\n' / 0x0A)
- Escape ('\e' / 0x1B): '\e' is not a standard escape character, despite
being widely supported, so we use 0x1B.
These match the control characters windows supports in WM_CHAR messages, according to MSDN:
https://docs.microsoft.com/en-us/windows/win32/inputdev/using-keyboard-input
Uplink's textinput code handles just Backspace, Enter, and Escape (notably, it does require that Enter gives 13 ('\r') rather than newline, as I'd initially …
=> Handle unicode control characters

src/SDL12_compat.c
It's possible for ``HandleInputGrab()`` — which is called by ``SDL_WM_GrabInput()`` — to dereference a NULL pointer when attempting to check if the window is fullscreen. Assume that, if ``VideoSurface12`` is NULL, we don't have a fullscreen window, and so shouldn't automatically grab.
This was causing Psychonauts to crash on startup, as it called ``SDL_WM_GrabInput()`` before ``SDL_SetVideoMode()``.
=> Handle SDL_WM_GrabInput() when VideoSurface12 is NULL

CMakeLists.txt, sdl12_compat.pc.in
In order to fully substitute for SDL 1.2, we need to be able to
install the headers and generate a compatible .pc (pkgconfig) file.
There's an option to not install it if it is not desired for some
reason.
Reference: https://fedoraproject.org/wiki/Changes/SDL12onSDL2
=> Install development headers and compatible pkgconfig file with CMake

src/SDL12_compat.c, src/SDL20_syms.h
While sdl12-compat scales the graphics for fullscreen windows running at a non-native resolution, mouse input is not scaled to match. Most games handle this relatively well — maybe the mouse gets "lost" off the right or bottom corners of the screen, which is only really obvious on dual-screen setups — but some will end up with the system/hardware cursor offset from where the game thinks it is.
For non-OpenGL applications, ``SDL_RenderSetLogicalSize()`` should scale the mouse coordinates for the window's events for us, but this has two problems:
1. We use ``SDL_SetEventFilter()`` to receive events, which runs before the Event Watch callback used by SDL_Renderer to scale the input.
2. Only events for the particular window are affected: the global coordinates returned by …
=> Use scaled mouse coordinates from SDL_RenderSetLogicalSize()

src/SDL12_compat.c
While ``SDL_SetAlpha()`` should ignore the "whole-surface alpha" value, it should still succeed for surfaces which have an alpha channel.
Commit b4acf4f08f implements this, but returns -1 for surfaces with an alpha channel, signaling an error. Given that we've actually successfully enabled/disabled blending, ``SDL_SetAlpha()`` has succeeded, even if a whole-channel alpha value wasn't set.
In fact, SDL 1.2 seems to never be able to return an error from ``SDL_SetAlpha()``.
This fixes Ren'py games, which use ``SDL_SetAlpha()`` on surfaces with an alpha channel, and check the return value. In particular, the Steam version of "Long Live the Queen", which uses Ren'py 6.12.2, broke in b4acf4f08f, and is fixed by this. ``testalpha`` seems to still work fine with this change, too.
=> SDL_SetAlpha() shouldn't fail on surfaces with alpha channels

src/SDL12_compat.c
This causes problems with programs which don't handle the combination of ``SDL_DOUBLEBUF`` on a surface which doesn't need locking (i.e. ``SDL_HWSURFACE`` not being set) properly.
DOSBox is one such application, so this fixes issue #58.
It also matches what the real SDL 1.2 exposes in most real-world circumstances.
Tested this against DOSBox (now works), Ren'py 6.12 /Long Live The Queen (continues to work), and ``testsprite`` (continues to work).
=> Don't set SDL_DOUBLEBUF on the screen surface

src/SDL12_compat.c, src/SDL20_syms.h
This change decouples the scaling used for Logical Scaling from ``SDL_RENDER_SCALE_QUALITY`` (which defaults to nearest-neighbour) for non-OpenGL based windows, and use linear scaling by default.
It also introduces the new ``SDL12COMPAT_SCALE_METHOD`` environment variable, which can be set to 'nearest' to get nearest neighbour filtering. 
OpenGL Logical Scaling now also support the ``SDL12COMPAT_SCALE_METHOD`` environment variable, so it's technically possible to have nearest-neighbour filtering for OpenGL applications. For anything actually 3D, though, this usually looks completely terrible.
Unless you're exceptionally lucky with your screen resolution being an integer multiple of the underlying game resolution, nearest-neighbour filtering looks terrible in most cases.
Ultimately, it'd …
=> Use linear filtering by default for Logical Scaling

test/testloadso.c, test/testoverlay.c
I'm not sure when we want to modify these from their original SDL 1.2 forms, but since there seem to have been some changes, here are fixes for the warnings I get on my machine.
In ``testoverlay``, the ``flip`` variable is never read from: the ``-flip`` option just requests ``SDL_DOUBLEBUF``. It's a useless variable, but not actively harming anything. This change just gets rid of the variable.
```
/home/david/Development/sdl12-compat/test/testoverlay.c: In function ‘main’:
/home/david/Development/sdl12-compat/test/testoverlay.c:324:6: warning: variable ‘flip’ set but not used [-Wunused-but-set-variable]
324 |  int flip;
|      ^~~~
```
In ``testloadso``, the return value variable ``retval`` is also never read from: ``main`` just returns 0 at the end, regardless of whether it's succeeded …
=> Fix a couple of compile warnings (and a bug) in SDL 1.2 test programs

src/SDL12_compat.c
[NOTE: I've only tested this on Linux, and only with DOSBox — it might totally break input for some applications on some platforms! All of the scancode values were entered by hand, too, so there may be a few which are wrong!]
As seen in issue #84, DOSBox uses SDL 1.2 scancodes by default. It _mostly_ copes with sdl12-compat's lack of scancode support by falling back to a different codepath, but this breaks on OS X because scancode 0 is 'A', and the fallback path doesn't completely support some keyboard layouts.
To remedy this, we try to support scancodes.
This chance introduces a new ``Scancode20to12()`` function to convert an SDL 2.0 scancode into an SDL 1.2 scancode. The actual conversion is platform specific, because the SDL 1.2 scancodes vary wildly between different platforms (and, …
=> Add rudimentary emulation of SDL 1.2 scancodes

src/SDL12_compat.c
Now that we have scancode and unicode values available, it's worth actually handling keys which might not have an SDLK_ value in SDL 1.2.
The motivating case here is DOSBox — see issue #84 — which uses scancodes for input by default. On some keyboard layouts, there are keys which have a valid scancode, but don't have a corresponding ``SDLK_`` value. For example, the 'ğ' key on the Turkish F layout sits where 'e' is on a US layout. There's no ``SDLK_ğ`` value for this to use, but the scancode is the same as for ``e``, so DOSBox should work anyway. However, the whole event is thrown out when the sym is ``SDLK_UNKNOWN``, so it never sees the scancode.
Note that this shouldn't really be a problem anyway, as SDL 1.2 — at least on my system — doesn't take the keyboard layout into consideration …
=> Propagate KEY{UP,DOWN} even if keycode is SDLK_UNKNOWN

test/checkkeys.c
It's useful for debugging what scancodes are used by SDL 1.2
(particularly across different platforms) if checkkeys displays it even
when it does successfully map it to an SDLKey.
In addition, print the scancode in hex as well as decimal, as the
hardcoded values we're using in sdl12-compat are all in hex.
Previously (for pressing 'a' and the 'Calculator' key on my keyboard), ``checkkeys`` would show:
```
Key pressed:  97-a  (a) modifiers: NUM
Key released:  97-a  modifiers: NUM
Unknown Key (scancode = 148) pressed  modifiers: NUM
Unknown Key (scancode = 148) released  modifiers: NUM
```
With this change, it now looks like:
```
Key pressed:  97-a (scancode = 38 [0x26]) (a) modifiers: NUM
Key released:  97-a (scancode = 38 [0x26]) modifiers: NUM
Unknown Key (scancode = 148 [0x94]) pressed …
```
=> checkkeys: Unconditionally display the scancode

CMakeLists.txt
A static link library is not ideal, since we cannot statically link
SDL2 into this library. However, some projects demand a static library
to build, so optionally provide a way to build it so those projects
can use this library instead of SDL-1.2.
=> cmake: Add support to build the static library

src/SDL12_compat.c
Given we allocate and use a bunch of wrappers around the SDL audio device, we should shut it down explicitly on quit.
The simplest way to implement this was to just call our ``SDL_CloseAudio()`` implementation in ``SDL_QuitSubsystem()``, which require making it robust against closing an already closed audio device.
This fixes a sporadic null pointer access in the audio callback on DOSBox on one of my machines.
=> Close audio device in SDL_Quit{,Subsystem}()

src/SDL12_compat.c
SDL2 expects 8-bit surfaces to have correct {R,G,B,A}masks in their format: either all 0 for paletted surfaces, or the correct values for ``SDL_PIXELFORMAT_RGB332``. Indeed, ``SDL_ConvertSurface()`` will crash if this
is not the case.
Some SDL 1.2 applications provide incorrect masks for paletted surfaces. We originally zeroed these out in 46fdbf7c1d, but 3af751b91b actually re-sets these in ``SetPalette12ForMasks()``.
Instead, do not set the masks on the SDL 2 surface in ``SetPalette12ForMasks()``, and force them to be 0 in ``PixelFormat12to20()` if there is a palette. The masks are still set on the SDL 1.2 surface's format, and the palette generated by SetPalette12ForMasks() should in theory make sure surfaces with 8-bit masks still work.
The other option, rather than making this depend …
=> Don't set {R,G,B,A}masks on SDL2 paletted surfaces

src/SDL12_compat.c, src/SDL20_syms.h
In SDL 1.2, ``SDL_PauseAudio()`` works from within the audio callback, whereas currently in sdl12-compat, it deadlocks due to ``SDL_LockAudio()`` being called.
Move the callback paused state out of the ``AudioCallbackWrapperData`` callback structure (whose allocation is protected by ``SDL_LockAudio()``) and into a separate atomic variable. ``SDL_PauseAudio()`` can then simply set that value.
This fixes some SDL 1.2 Ren'py games, which will deadlock somewhat randomly either at startup or when a new piece of music plays, due to ``SDL_PauseAudio()`` being called from within the callback.
There may be scope down the line for having sdl12-compat have a custom ``SDL_LockAudio()`` implementation which doesn't interfere with the CD audio playback, too, but even then ``SDL_PauseAudio()`` couldn't …
=> SDL_PauseAudio should work within the callback

src/SDL12_compat.c
When the mouse is in Relative Mode (MouseInputIsRelative is true), we
"fake" the mouse position by integrating the relative coordinates
(adding them to the MousePosition variable, which accumulates the
position over time).
However, only SDL_GetMouseState() would actually use these
coordinates, events still used the raw position from the system
(possibly scaled, as both the SDL_RenderSetLogicalSize() and OpenGL
based scaling only affects the position, not the relative values). This
creates a mismatch: mouse coordinates received from events don't match
those received from SDL_GetMouseState().
Instead, we should update the mouse coordinates of the SDL 1.2 events
produced to match what we're keeing in the MousePosition variable. We
also do this for mouse button events, as otherwise clicks …
=> Mouse position should be consistant between events and GetMouseState in relative mode

src/SDL12_compat.c
If the program creates several windows (such as Unreal Tournament 2004's
splash screen), the Event Filter used to convert SDL 2.0 events to SDL
1.2 events can end up being added twice, which causes events to be
converted twice).
Unconditionally remove the event filter in Init12Video() before
adding it, to ensure it only ever appears once. This fixes issue #119.
=> Don't add the 2.0->1.2 event conversion filter twice

CMakeLists.txt
This prevents undefined references to `WinMain@16` by consumers.
(From @manisandro for [the Fedora `mingw-sdl12-compat` package](https://src.fedoraproject.org/rpms/mingw-sdl12-compat/c/60d858f997a3f0ca137ff1dd2135c462cf0eda21?branch=rawhide))
=> Add `-lmingw32` to `SDL_LIBS`

src/SDL12_compat.c, src/SDL20_syms.h
The SDL_Render-based logical scaling (using ``SDL_RenderSetLogicalSize()``) will scale both the relative and absolute mouse inputs, whereas we were only scaling the absolute mouse position. To match the SDL_Render mode, this change adds relative mouse motion scaling to the OpenGL Logical Scaling code, as well as the ability to disable it with the ``SDL_MOUSE_RELATIVE_SCALING`` environment variable (already supported by SDL_Render).
Note that the actual difference in behaviour here is extremely subtle, and hasn't been causing any actual issues as far as I can tell, but it could "feel" a little bit weird, particularly on games which were using relative mouse motion to control a cursor.
Most of these issues were fixed in SDL 2.0 as a result of this bug report: …
=> Scale relative mouse coordinates when OpenGL Logical Scaling is in use

src/SDL12_compat.c
The recommended way to handle ``VIDEORESIZE`` is with a new ``SDL_SetVideoMode()`` call, and creating a new window generates a ``SIZE_CHANGED`` event, which leads to an infinite loop. The other main case for ``SIZE_CHANGED`` events is when the screen resolution is changed out from underneath a fullscreen window, and we handle that with the logical scaling.
So it doesn't appear that there's any use for ``SIZE_CHANGED`` events in SDL 1.2 applications. So let's just ignore them. This fixes Drawf Fortress in bug #127.
The other possible fix is to check if a SIZE_CHANGED event has the same size as the current window anyway (and is therefore a no-op), and discard it if so. But there's no easy record of the previous resolution which exists across both OpenGL and non-OpenGL windows, so it didn't …
=> Do not generate VIDEORESIZE events on SIZE_CHANGED (fix #127)

src/SDL12_compat.c
Resizable SDL 1.2 windows are really annoying to use when the window gets repeatedly recreated, as (at least on some window managers) this resets the resize operation.
This follows on from bug #127, as Dwarf Fortress hits this issue, being a resizable window which calls ``SDL_SetVideoMode()`` on every ``SDL_VIDEORESIZE`` event. With this change, resizing now seems to work identically to the SDL 1.2 version.
I'm not sure why we explicitly disabled this, though, so maybe there's a regression somewhere I don't know about. If so, maybe this is something we only do for ``SDL_RESIZABLE`` windows, or something?
=> Don't recreate the window on resize, even in windowed mode

src/SDL12_compat.c
For non-OpenGL applications, the ``SDL12COMPAT_SYNC_TO_VBLANK`` environment variable could be used to enable/disable VSync. For OpenGL applications, this was always able to be controlled by the application, using the ``SDL_GL_SWAP_CONTROL`` attribute. However, some old games do not provide a simple mechanism for configuring VSync (and so either don't set ``SDL_GL_SWAP_CONTROL``, or always set it to an undesirable value).
Allow the ``SDL12COMPAT_SYNC_TO_VBLANK`` environment variable to override the ``SDL_GL_SWAP_CONTROL`` attribute for OpenGL windows. The existing behaviour remains if ``SDL12COMPAT_SYNC_TO_VBLANK`` is not set.
(Also remove a FIXME() which was obsolete.)
=> Support SDL12COMPAT_SYNC_TO_VBLANK for OpenGL apps

src/SDL12_compat.c
It looks like (at least out of the top three of Windows, Mac, and Linux), only Windows forces the use of the US layout. Mac (at least from a cursory reading of the code), translates according to the keyboard layout, as does X11 (albeit with some bugs).
In this case, set the default to disable layout translation only on Win32, and have it enabled by default on other platforms.
This does break DOSBox, but only when "usescancodes = false" (or potentially if keyboard layouts changed some of the non-printable character keys which would break out scancode fallback). Since this is not the default, hopefully people won't encounter it…?
=> Make SDL12COMPAT_USE_KEYBOARD_LAYOUT's default platform-specific.

src/SDL12_compat.c, test/checkkeys.c
.. at least on platforms that use UTF-8, like modern Linux (Windows should work as well as before).
Also unified the output to print sth like "'Ä' (0x00C4)", i.e. both the actual char and the unicode constant, on all platforms.
Before these changes, on Linux it would print garbage or nothing for the unicode character, if it wasn't from the ASCII range
=> checkkeys test: Improve printing of Unicode-Chars

src/SDL12_compat.c, src/SDL20_syms.h
[I'm happy to split one or all of these out into separate PRs if some are more controversial than others.]
This is a bunch of changes related to various FIXMEs in the sdl12-compat code, as noted in #143. This change includes:
- ``glRenderbufferStorate()`` is a part of core GL 3, so get rid of the fixme reminding us to check.
- ``SDL_VIDEO_FULLSCREEN_DISPLAY`` was only partly supported, complete it.
- Make the timing of presentations in UpdateRects and when handling YUV overlays refresh-rate dependent.
- Add a very basic ``SDL_EnableKeyRepeat()`` implementation which ignores the delay/interval and just uses SDL2's repeat field.
(Largely in order from least to most controversial.) The only real issues I can imagine are:
- The ``GetEnvironmentWindowPosition()`` function now sets x and y …
=> Bunch of FIXME-related fixes

README.md
Add two sections to the README about different compatibility issues:
1. Issues with OpenGL Scaling
2. Other issues with apps which access APIs directly.
In both cases, this is usually the fault of an OpenGL extension loader,
sometimes deep in a library.
=> Add some notes about compatibility issues to the README (issue #144)

src/SDLmain/macosx/SDLMain.h, src/SDLmain/macosx/SDLMain.m
These clean up deprecation warnings, etc, in macos's SDLmain code.
Fixes #106. (at least, it fixes the last remaining items on that issue.)
=> Macos deprecation fixes

src/SDL12_compat.c
Many existing OpenGL games don't handle the window-size/drawable-size mismatch that exists on High-DPI systems. We handle this for them when OpenGL Logical Scaling is used, but when it's been disabled (possibly because it's never enabled for windowed-mode), we should not mark our windows as DPI-aware.
Fixes issues with Psychonauts (renders to the corner of the screen) and Darwinia (some UI elements misaligned, only a quarter of the screen fades) when run with ``SDL12COMPAT_OPENGL_SCALING=0`` on a 2× scaled Wayland display.
=> Disable HIGHDPI support by default for unscaled OpenGL apps

CMakeLists.txt, sdl-config.in, sdl12_compat.pc.in
As we've decided that the emulated SDL version will be the project
version for sdl12-compat, unify and simplify the versioning constructs
throughout the project so we only have to deal with versioning in
one place.
=> cmake: Rewire and simplify project versioning

src/SDL12_compat.c
Some applications, such as mplayer with ``-vo sdl`` will access the ``pixels`` member of an ``SDL_Overlay`` immediately after creating it, without ever locking it. This works on (at least some backends for) SDL 1.2, but crashed on sdl12-compat, as pixels remained unset until ``SDL_LockYUVOverlay()`` is called.
Set ``pixels`` in ``SDL_CreateYUVOverlay()``, as well as ``hwdata->dirty``, which
makes it possible to have a working YUV overlay without ever locking/unlocking it. This is required for mplayer's sdl vo backend to function.
Fixes issue #164.
=> Set 'pixels' in SDL_CreateYUVOverlay() (Fix #164)

src/SDL12_compat.c
``SDL_Surface`` has a ``refcount`` field, and surfaces shouldn't be destroyed until it's zero.
Confusingly, in sdl12-compat, there are two ``refcount`` fields: one for the SDL 1.2 surface, and one for the SDL 2.0 surface used to implement it.
There are two ways this could be implemented:
1) Keep the SDL12_Surface and SDL20_Surface refcounts synchronised across every call into SDL2.
2) Completely separate the refcounts.
This implements option 2: the SDL12_Surface's refcount is set to 1 when created, not to be equal to the SDL2 surface's refcount. We then decrement this and free it as required.
This is safe for two reasons:
- As long as the 1.2 surface's refcount is > 0, there must be at least one reference to the 2.0 surface.
- It turns out nothing in SDL 2 is actually using the SDL 2 …
=> Handle SDL12_Surface::refcount in SDL_FreeSurface

src/SDL12_compat.c
(Whoops, we forgot to update this for 1.2.52. :/)
This is used by SDL_Linked_Version().
Maybe it'd make sense to inject this from the build system, which should
already know what the version is. In the meantime, however, report
1.2.53.
=> Update SDL12_COMPAT_VERSION to 53 for 1.2.53

src/SDL12_compat.c, src/SDL20_include_wrapper.h
This follows the discussion in #168 and introduces a "quirks" table which allows application-specific workarounds to be implemented.
Basically, it works by adding an ``SDL12Compat_GetHint()`` function to replace the various ``getenv`` calls around the place, and makes that check an array of (executable name, hint name, hint value) tuples.
The list of quirks is platform-specific, and keyed on the executable filename (hence there being duplicates for different architectures).
I've also added a workaround for the Awesomenauts issue in bug #168, though it's a bit hacky.
I've also not added, e.g., Dynamite Jack, whose executable name is — I think — just "main". Things like driconf and vkd3d-proton's system support fancier ways of selecting these (with wildcards, or executable hashes, etc), but …
=> Implement an application-compatibility "quirks" system (and hacky workaround for Awesomenauts)

src/SDL12_compat.c
For some reason, the Steam build of Multiwinia seems to be missing a call to ``SDL_Init()`` where the (older) non-Steam builds have one. This results in the game, when a resolution change is requested:
- Calling ``SDL_QuitSubsystem(SDL_INIT_VIDEO)`` when the old window is
destroyed.
- **NOT** calling ``SDL_Init(SDL_INIT_VIDEO)`` when creating the new window (unlike the non-Steam builds).
- Calling ``SDL_GetVideoInfo()``, and promptly asserting when NULL is
returned.
- (And then proceed to create a window, which will fail, etc…)
This issue _is_ reproducable under real SDL 1.2 (though with
SDL_VIDEO_FULLSCREEN_HEAD set, no other modes are listed, so it's
difficult to trigger), but it seemed worth working around.
To do so, simply make ``SDL_QuitSubsystem()`` mask out ``SDL_INIT_VIDEO``. This …
=> quirk: Disable SDL_QuitSubsystem(SDL_INIT_VIDEO) for Multiwinia/steam

include/SDL/SDL_config.h
BSDs have alloca() defined in stdlib.h. It's in alloca.h on
Linux and illumos.
=> BSD support: Don't assume alloca.h is available on Unix

src/SDL12_compat.c
We're currently using SDL_PIXELFORMAT_RGB24, which results in
schismtracker being blue when resized (#183).
While it's possible that RGB888 is wrong on big-endian systems, it at
least matches what we do for 16-bit (RGB565) and 32-bit (XRGB8888)
formats, so if we're wrong, we'll at least be consistently wrong.
=> Use SDL_PIXELFORMAT_RGB888 for 24-bit surfaces

include/SDL/SDL_stdinc.h
This should offer better compatibility in some cases.
This PR is an alternative to #195. I think that one is probably better practice in general, but this one is taking more of a bug-for-bug compatibility approach, as may better fit the goals of sdl12-compat.
=> Make include logic closer to real SDL 1.2

CMakeLists.txt
The compatibility_version is meant to go up when new symbols are added
to a library, so an executable built against an older version of a
library can run against a newer version of that library, but not the
other way round. The most binary compatible approach is therefore to
use the highest of the different compatibility_version numbers that
could have been used by SDL-1.2.
=> Set DYLIB_COMPAT_VERSION to match SDL-1.2 autotools

src/SDL12_compat.c
Since commit 812d58f, SaveDestAlpha only acts on a rectangle of size (dstrect12->w × dstrect12->h) at (dstrect12->x, dstrect12->y), but RestoreDestAlpha tries to act on a rectangle of size (dst12->w × dst12->h) at (dstrect12->x, dstrect12->y). For a non-trivial dstrect with x > 0 or y > 0, this resulted in invalid accesses outside the bounds of the pixel buffer and memory corruption.
Fixes: 812d58f "video: Optimize temporarily saving of dest alpha for a blit"  
Resolves: https://github.com/libsdl-org/sdl12-compat/issues/211
=> RestoreDestAlpha: Fix out-of-bounds access to buffer

test/testiconv.c
This helps make it more clear at a glance whether or not testiconv succeeded or not.
This change is copied from libsdl-org/SDL-1.2#868.
=> testiconv: Print the total number of errors at the end

src/SDL12_compat.c
When we're logically scaling, and preserving the aspect ratio (so are letterboxing or pillarboxing), the scaled mouse coordinates may be outside the application window (backbuffer). These can even be negative, which get underflowed to very large positive values, as SDL 1.2 uses unsigned coordinates here.
We were already clamping these values for OpenGL logical scaling, which we do ourselves, but the event filter used with SDL_Renderer doesn't, so we'll manually clamp these all the time.
The issue could be reproduced in Civilization: Call To Power, by starting the game windowed 1024×768 (or another 4:3 resolution), maximising the window (which, if you have a widescreen display, will pillarbox), and starting a game. When pushing the mouse to the left edge to scroll, you have to very …
=> Clamp mouse coordinates to the backbuffer size for non-OpenGL

CMakeLists.txt
- find SDL2 through [`find_package`](https://cmake.org/cmake/help/latest/command/find_package.html)
- prepend all values in `CMAKE_DL_LIBS` with `-l`, for use in the `.pc` file.
The CMake script unconditionally uses `dl`, even if `dlopen` is available in the c library.
This is also what's documented in the [dlopen manual](https://man7.org/linux/man-pages/man3/dlopen.3.html).
Fixes #222
=> cmake: make sure all libraries in CMAKE_DL_LIBS are added with -l prefix to .pc file

src/SDL12_compat.c
We were accidentally using the frame number instead of the track number to lookup a track, which not only resulted in playback cutting off in the middle of tracks, but also probably accessed a bunch of invalid memory.
This fixes CivCTP, which does still seem to play each track twice in a row, though that might be the game's intended behavour. Otherwise (along with one more nasty binary patch to work around the game's recursive mutex implementation) it now is absolutely rock-solid on my machines.
=> cdrom: Fix end offset calulcation in SDL_CDPlay

src/SDL12_compat.c
crrcsim, a model aeroplane simulator, is linked to both SDL 1.2 and plib. I'm not entirely sure why, since plib seems to be an (unmaintained) alternative to SDL that did many of the same things.
Because plib has a C++ ABI but dlsym() works with C-level ABI, we need to use a C++ mangled name for the symbol we look for.
Resolves: https://github.com/libsdl-org/sdl12-compat/issues/252
=> quirks: Force X11 if plib (specifically libplibssg) is detected

src/SDL12_compat.c
=> Fix missing format string argument in low-bit-depth workaround

src/SDL12_compat.c
Steel Storm (and presumably other darkplaces, SDL 1.2-based games) expect x11.wmwindow to be valid if they've created a window and are running under X11. Just pass the same game window like we do for x11.window.
See the old darkplaces code here:
https://github.com/xonotic/darkplaces/blob/a0465ad2ee16719587b0b7a80d4c1c2f7df1ac0e/vid_sdl.c#L2334
This should fix the BadWindow errors on Steel Storm Burning Retribution (issue #290)
=> SysWW/X11: Return the X11 window as wmwindow and x11window

include/SDL/SDL_platform.h
Prevents some versions of clang from erroring out like this:
```
error: 'TARGET_OS_TV' is not defined, evaluates to 0 [-Werror,-Wundef-prefix=TARGET_OS_]
```
=> Check for undefined TARGET_OS_*

include/SDL/SDL_video.h
Classic SDL 1.2 headers traditionally had this member as a pointer to the incomplete type `struct private_hwdata`. For whatever reason (presumably a sense of completeness) the SDLmm C++ binding[1] that is bundled in Debian package 'asc' (Advanced Strategic Command) defines an accessor for it, which is declared as returning `struct private_hwdata *` and has the obvious trivial implementation[2].
Implicit conversion from `void *` to `struct private_hwdata *` is allowed in C, but not in C++, so sdl12-classic's simplification of changing this member from `struct private_hwdata *` to `void *` breaks the build for SDLmm.
Arguably it's a bug that SDLmm has this accessor, because this member is for internal use by SDL and its type has no public definition, so there's no legitimate reason for …
=> include: Use `struct private_hwdata` incomplete type for API compat

src/SDL12_compat.c
Native SDL 1.2 and 2.0 both handle SDL_LoadWAV(null,...), SDL_LoadWAV("",...) and SDL_LoadWAV(nonexistent_file,...) by returning NULL and setting an error; this check resores that behavior.
Fixes https://github.com/libsdl-org/sdl12-compat/issues/310
=> Add null check to SDL_LoadWAV_RW to avoid crashes

src/SDL12_compat.c
In #305, we have trouble with libsdl-perl making assumptions about the video surface never being freed or reallocated, and it being a no-op to "free" the video surface.
There is nothing that says a SDL 1.2 surface must always wrap the same SDL 2 surface, so we can maybe accommodate those assumptions by having the video surface be a special-cased global pointer that is never freed, and only reallocate its contents?
This seems to work with libsdl-perl's `core_video.t` test, but I haven't tested it extensively; consider it a proof-of-concept for now.
* Factor out Surface20to12InPlace
This is a step towards making it possible to use the same SDL12_Surface
for the video surface at all times, and only reallocating its underlying
SDL 2 SDL_Surface.
* Factor out FreeSurfaceContents, and handle …
=> Allocate video surface object statically as a global

src/SDL12_compat.c
=> Quirks: Mark of the Ninja (humble bundle) needs OpenGL scaling disabled.

src/SDL12_compat.c
sdl12-compat tracks the mouse position in the MousePosition variable, even when we're not in relative mouse mode. We therefore don't need to call SDL20_GetMouseState() to update it before entering relative mouse mode: we already have it from the last SDL_MOUSEMOTION event, and have already applied any scaling we need.
This is important, because SDL_GetMouseState() returns the _raw_ mouse coordinates, not the ones scaled by SDL_RenderSetLogicalSize(). So we end up with a mismatch. This results in a mouse offset on non-OpenGL, scaled games, like Alpha Centauri in fullscreen (see #318).
We could fix this by calling SDL_RenderWindowToLogical() instead, but that complicates the codepath as we don't always have an SDL_Renderer (we might be using OpenGL), so this seems cleaner.
I've tested this …
=> Avoid SDL_GetMouseState(), which returns raw coordinates (fixes #318)

src/SDL12_compat.c
Some games (e.g. Hyperspace Delivery Boy) only work on a 16-bit display,
but request the highest bit-depth available. Add a hint which makes all
queries for a mode (including the current mode, and the implicit format
chosen by providng SDL_SetVideoMode() a bpp of 0) report a bit depth
less than or equal to the value of SDL12COMPAT_FORCE_BPP.
We then add a quirk to force Hyperspace Delivery Boy to 16-bit, as it uses
the current video mode's bpp, but for 32-bit modes relies heavily on the
exact way format conversion was broken in some SDL 1.2 versions.
There are a few interesting "features" of this implementation:
- All video modes are now clamped to 32bit, which is the default value
of the hint. This seems like something we'd probably want anyway, as
many SDL 1.2 apps would have trouble …
=> Add a SDL12COMPAT_MAX_BPP hint, and use it to restrict Hyperspace Delivery Boy to 16bpp (fixes #317)

src/SDL12_compat.c
unless I'm missing something obvious, `c` is never equal to zero
=> cdrom: fix 'no track 1' edge case

sdl.m4
When cross-compiling, pkg.m4 will set the PKG_CONFIG variable to a suitable pkg-config executable, which might be a host-architecture-prefixed name like aarch64-linux-gnu-pkg-config. This ensures that we will use a suitable search path that is suitable for the host architecture (the machine we are compiling for) rather than the build architecture (the machine we are compiling on) to find dependency libraries like SDL. When using pkg-config as a substitute for sdl2-config, we will similarly need to use the host-architecture-prefixed pkg-config.
Setting the PKG_CONFIG environment variable is also the canonical way to request that a different pkg-config implementation be used, if that becomes necessary for some reason.
Bug-Debian: https://bugs.debian.org/1059749
=> sdl.m4: Call $PKG_CONFIG rather than hard-coding pkg-config

README.md
This hint was never documented in README.md, even though it was used in a quirk, and mentioned briefly in COMPATIBILITY.md.
There's possibly a point where README.md might not be the best place for an exhaustive list of hints/quirks, particularly if they get very obscure or game-specific. Though given this now seems to help multiple applications, it's probably okay. But maybe we'll get to a point where it's worth only mentioning the most common in README.md, and moving the rest to a separate HINTS.md.
Fixes #329.
=> README: Document SDL12COMPAT_NO_QUIT_VIDEO

src/SDL12_compat.c
Don't ask my why this is needed, but without it the game just freeze/crash after the intro video:
```
INFO: This app is looking for CD-ROM drives, but no path was specified
INFO: Set the SDL12COMPAT_FAKE_CDROM_PATH environment variable to a directory
INFO: of MP3 files named trackXX.mp3 where XX is a track number in two digits
INFO: from 01 to 99
double free or corruption (!prev)
BUG!  Exception triggered, cleaning up.
Heroes of Might & Magic III 1.3.1a
Built with glibc-2.1 on x86
Stack dump:
{
```
=> quirks: Add SDL12COMPAT_COMPATIBILITY_AUDIOCVT=1 to "heroes3.dynamic"

src/SDL12_compat.c
doukustu.bin is the original executable of Cave Story's Linux port (1.01). Unlike the later v1.2 versions, the original version doesn't use audio correctly and thus requires this fix.
The French version notably ships with this 1.01 executable instead of the v1.2 ones.
Fixes #335
=> quirks: Add SDL12COMPAT_COMPATIBILITY_AUDIOCVT=1 to "doukutsu.bin".

CMakeLists.txt
When building `sdl12-compat` in a subdirectory of another project using cmake's [add_subdirectory](https://cmake.org/cmake/help/latest/command/add_subdirectory.html) command directly or indirectly with [FetchContent](https://cmake.org/cmake/help/latest/module/FetchContent.html) currently some paths don't work properly. The reason is that in this case `CMAKE_SOURCE_DIR`/`CMAKE_BINARY_DIR `points to the respective directory in the root project instead. 
I replaced all occurrences of  `CMAKE_SOURCE_DIR` with `CMAKE_CURRENT_SOURCE_DIR` and `CMAKE_BINARY_DIR` with `CMAKE_CURRENT_BINARY_DIR`.
=> Make build work when used with FetchContent or add_subdirectory

src/SDL12_compat.c
Code depends on being able to see the RESIZABLE flag in video surfaces. For example, the Perl module SDLx::App will throw an error if it tries to resize a surface but doesn't find SDL_RESIZABLE in its flags:
<https://metacpan.org/release/FROGGS/SDL-2.548/source/lib/SDLx/App.pm#L143>
To improve compatibility with such code, copy the flag to the VideoSurface12 created in SDL_SetVideoMode.
=> video: Reflect SDL12_RESIZABLE in SDL12_Surface->flags

CMakeLists.txt, sdl12_compat.pc.in
This is unnecessary, given that everyone uses `pkgconf(1)`, which fully supports the `Provides:` stanza and expresses it in dependencies.
This reverts commit f10920239783dc09bd22f09bad69585cfce8a28d.
=> Revert "Rename sdl12_compat.pc to sdl.pc"

src/SDL12_compat.c
SDL_CreateRGBSurface currently asserts that SDL_PREALLOC is not set. However, if the surface is empty (width or height are zero), then it doesn't matter if pixels is valid.
SDL2 does allocate an "empty" pixels, and so doesn't set SDL_PREALLOCATED, but SDL3 (including via sdl2compat) doesn't, leaving the empty SDL_Surface with SDL_PREALLOCATED (so it doesn't try to free the NULL pointer).
This _could_ be worked around in sdl2compat, but the SDL3/sdl2compat behaviour does make sense, and it's only the zealous assertion here which breaks.
Civilization: Call To Power triggers this by trying to create a bunch of 0×0 surfaces at startup, and is fixed by this patch.
Fixes: 13efe605cc42 ("Factor out enough of SDL_CreateRGBSurface to create surfaces in-place")
=> SDL_CreateRGBSurface: Don't assert SDL_PREALLOC not set on 0-sized surfaces (width and/or height are 0)
